/*****************************************************************************
* Model: model.qm
* File:  ./blinky.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${AOs::.::blinky.c} ......................................................*/
#include "qp_port.h"
#include <stdio.h>
#include <stdlib.h>

#define BSP_TICKS_PER_SEC 100


void Q_onAssert(char const Q_ROM * const Q_ROM_VAR file, int line) {
    fprintf(stderr, "Assertion failed in %s, line %d", file, line);
    exit(0);
}
void QF_onStartup(void) {}
void QF_onCleanup(void) {}
void QF_onClockTick(void) {
    QF_TICK((void *)0);
}

enum BlinkySignals {
    TIMEOUT_SIG = Q_USER_SIG,
    MAX_SIG
};

/*************** ask QM to declare the Blinky class ******************/
/*${AOs::Blinky} ...........................................................*/
typedef struct {
/* protected: */
    QMActive super;

/* private: */
    QTimeEvt timeEvt;
} Blinky;

/* protected: */
static QState Blinky_initial(Blinky * const me, QEvt const * const e);
static QState Blinky_off  (Blinky * const me, QEvt const * const e);
static QState Blinky_off_e(Blinky * const me);
static QMState const Blinky_off_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Blinky_off),
    Q_ACTION_CAST(&Blinky_off_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState Blinky_on  (Blinky * const me, QEvt const * const e);
static QState Blinky_on_e(Blinky * const me);
static QMState const Blinky_on_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Blinky_on),
    Q_ACTION_CAST(&Blinky_on_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};


/*************** ask QM to define the Blinky class  ******************/
/*${AOs::Blinky} ...........................................................*/
/*${AOs::Blinky::SM} .......................................................*/
static QState Blinky_initial(Blinky * const me, QEvt const * const e) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* transition-action table */
        &Blinky_off_s, /* target state */
        {
            Q_ACTION_CAST(&Blinky_off_e), /* entry */
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${AOs::Blinky::SM::initial} */
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);

    return QM_TRAN_INIT(&tatbl_);
}
/*${AOs::Blinky::SM::off} ..................................................*/
/* ${AOs::Blinky::SM::off} */
static QState Blinky_off_e(Blinky * const me) {
    BSP_ledOff();
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return QM_ENTRY(&Blinky_off_s);
}
/* ${AOs::Blinky::SM::off} */
static QState Blinky_off(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::Blinky::SM::off::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* transition-action table */
                &Blinky_on_s, /* target state */
                {
                    Q_ACTION_CAST(&Blinky_on_e), /* entry */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*${AOs::Blinky::SM::on} ...................................................*/
/* ${AOs::Blinky::SM::on} */
static QState Blinky_on_e(Blinky * const me) {
    BSP_ledOn();
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return QM_ENTRY(&Blinky_on_s);
}
/* ${AOs::Blinky::SM::on} */
static QState Blinky_on(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::Blinky::SM::on::TIMEOUT} */
        case TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* transition-action table */
                &Blinky_off_s, /* target state */
                {
                    Q_ACTION_CAST(&Blinky_off_e), /* entry */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}


static Blinky l_blinky;
QActive *AO_Blinky = &l_blinky.super;

static void Blinky_ctor(void) {
    Blinky *me = (Blinky *)AO_Blinky;
    QMActive_ctor(&me->super, Q_STATE_CAST(&Blinky_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}

int main() {
    static QEvt const *blinky_queueSto[10];

    Blinky_ctor();
    QF_init();

    QActive_start(AO_Blinky, 1U,
                  blinky_queueSto, Q_DIM(blinky_queueSto),
                  (void *)0, 1024U, (QEvt *)0);
    return QF_run();
}
